name: Build Windows Executable

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: windows-latest  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download PyInstaller
      run: |
        curl -Lo pyinstaller.tar.gz https://github.com/pyinstaller/pyinstaller/releases/download/v4.7/PyInstaller-4.7.tar.gz
        tar -xzf pyinstaller.tar.gz
        rm pyinstaller.tar.gz
        
    - name: Build executable
      run: |
        ./PyInstaller-4.7/pyinstaller.py --onefile src/order_images.py  
        
    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: dist/order_images.exe
