name: Build Windows Executable

on:
  push:
    branches:
      - main 

jobs:
  build-windows:
    runs-on: windows-2019  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Python
        uses: actions/setup-python@v1
        with: 
          python-version: '3.8'
          architecture: 'x64'

      - name: Install requirements
        run: |
          pip install -r requirements.txt
      
      - name: Run PyInstaller
        run: |
          python -m PyInstaller order_images.spec
        
      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: order_images
          path: dist/order_images.exe